ARG JAVA_BASE=11-jdk-openj9
FROM adoptopenjdk:${JAVA_BASE}
ENV JAVA_VERSION=${JAVA_BASE}

VOLUME /tmp

COPY ./target/yalsee.jar /app/
COPY ./docker-entrypoint.sh /
ADD https://search.maven.org/remotecontent?filepath=co/elastic/apm/elastic-apm-agent/1.20.0/elastic-apm-agent-1.20.0.jar /apm-agent.jar

RUN sh -c 'chmod +x /docker-entrypoint.sh'
RUN apt-get update && apt-get install -y haveged netcat curl jq

ENTRYPOINT ./docker-entrypoint.sh

EXPOSE 8080

HEALTHCHECK --start-period=60s --interval=5s --timeout=20s --retries=3 \
   CMD curl --silent --request GET http://127.0.0.1:8080/actuator/health \
                   | jq --exit-status '.status == "UP"' || exit 1
