FROM oraclelinux:7-slim
# Add Spring Boot Native app spring-boot-graal to Container
COPY ./target/native-image/yalsee /

VOLUME /tmp

COPY ./native-entrypoint.sh /

RUN sh -c 'chmod +x /native-entrypoint.sh && chmod +x /yalsee'
ENTRYPOINT ./native-entrypoint.sh

EXPOSE 8080

HEALTHCHECK --start-period=60s --interval=5s --timeout=20s --retries=3 \
   CMD curl --silent --request GET http://127.0.0.1:8080/actuator/health \
                   | jq --exit-status '.status == "UP"' || exit 1
