<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Yalsee two step verification code</title>
</head>

<body style="-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; height: 100%; line-height: 25px; width: 100% !important; margin: 0;"
      bgcolor="#f6f6f6">
<style type="text/css">
    body {
        margin: 0;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        box-sizing: border-box;
        font-size: 16px;
        color: #333;
        line-height: 25px;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: none;
    }

    body * {
        margin: 0;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        box-sizing: border-box;
        font-size: 16px;
        color: #333;
        line-height: 25px;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: none;
    }

    img {
        max-width: 100%;
        border: none;
    }

    body {
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: none;
        width: 100% !important;
        height: 100%;
        line-height: 25px;
    }

    body {
        background-color: #f6f6f6;
    }

    @media only screen and (max-width: 600px) {
        body {
            padding: 0 !important;
        }

        .container {
            padding: 0 !important;
            width: 100% !important;
        }

        .content {
            padding: 0 0 10px 0 !important;
        }

        .content-wrap {
            padding: 10px !important;
        }

        .main {
            border-right: none !important;
            border-left: none !important;
            border-radius: 0 !important;
        }

        .logo {
            padding-top: 10px !important;
        }

    }

    @media only screen and (min-width: 600px) {
        .content-table {
            width: 600px !important;
        }
    }
</style>
<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f6f6f6">
    <tr>
        <td class="container" width="100%" align="center">
            <table cellpadding="0" cellspacing="0" width="100%" class="content-table">
                <tr>
                    <td></td>
                    <td class="content" align="center" valign="top" width="600" style="padding-bottom: 20px;">
                        <table class="header" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td valign="middle" class="aligncenter middle logo" style="padding: 20px 0 10px;"
                                    align="center">
                                    <img src="https://dev.yals.ee/images/logo.png" alt="" width="39" height="39"/>
                                </td>
                            </tr>
                        </table>
                        <table class="main" cellpadding="0" cellspacing="0"
                               style="border: 1px solid #e9e9e9; border-radius: 3px;" bgcolor="white">
                            <tr>
                                <td class="content-wrap"
                                    style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; margin: 0; -webkit-font-smoothing: antialiased; padding: 20px; -webkit-text-size-adjust: none;"
                                    valign="top">

                                    <table width="100%" cellpadding="0" cellspacing="0"
                                           style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">
                                        <tr style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">
                                            <td class="content-block"
                                                style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; margin: 0; -webkit-font-smoothing: antialiased; padding: 0 0 10px; -webkit-text-size-adjust: none;"
                                                valign="top">
                                                Your two-step verification code is: <b
                                                        style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">${code}</b>
                                            </td>
                                        </tr>
                                        <tr style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">
                                            <td class="content-block last"
                                                style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; margin: 0; -webkit-font-smoothing: antialiased; padding: 0; -webkit-text-size-adjust: none;"
                                                valign="top">
                                                Use this code to complete logging in with Yalsee.
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td></td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>