version: '3'

networks:
  net:

services:
  # Database
  db:
    image: kio.ee/hub/library/postgres:15.1-alpine
    volumes:
      # ./postgres - is folder on host
      - ./postgres15:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_salaSana
    networks:
      - net
  # PG Admin4
  pga:
    depends_on:
      - db
    image: kio.ee/hub/dpage/pgadmin4:6.17
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: axe@axe.pm
      PGADMIN_DEFAULT_PASSWORD: AXtYcRuhGZCkZVv4xLpgjpLVd
    networks:
      - net
    volumes:
      # ./pgadmin - is folder on host
      - ./pgadmin:/var/lib/pgadmin
  # Redis
  redis:
    image: kio.ee/hub/library/redis:7.0.5-alpine
    command: [ "redis-server","--requirepass", "redis-password" ]
    restart: always
    ports:
      - '6379:6379'
    volumes:
      # ./redis - is folder on host
      - ./redis:/data
    environment:
      MASTER: true
      REDIS_AUTH: redis-password
    networks:
      - net
  # redis-commander
  redcom:
    image: kio.ee/hub/rediscommander/redis-commander:latest
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - ./redis.connections.json:/redis-commander/config/local-production.json:ro
    environment:
      - REDIS_HOSTS=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis-password
      - VIEW_JSON_DEFAULT=all
    networks:
      - net
