name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  buildTag:
    name: Build Tag
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1

      - name: Compile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.PROD
          push: true
          tags: kyberorg/yalsee:${{ steps.get_tag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
