name: "Deploy draft"

on: [push]

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Complile
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Login to Hub
        uses: docker/login-action@v1
        with:
          registry: hub.kyberorg.io
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.DEV
          push: true
          tags: hub.kyberorg.io/kyberorg/yalsee:dev

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEV_HOOK }}

      - name: Wait for deploy
        run: sleep 120

      - name: Test App
        run:  mvn -Dtest.url=https://dev.yals.ee -Dgrid.hostname=http://127.0.0.1:4444 -Dselenide.browser=chrome -Dtest.buildName=void -Dapp.shortUrl=https://d.yls.ee -Dsurefire.rerunFailingTestsCount=2 clean test
