name: "Ship to PROD"

on:
  push:
    branches:
      - trunk

jobs:
  ship2prod:
    name: Ship::PROD
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to gcr.kyberorg.io
        uses: docker/login-action@v1
        with:
          registry: gcr.kyberorg.io
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Complile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.PROD
          push: true
          tags: gcr.kyberorg.io/kyberorg/yalsee:prod

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.PROD_DEPLOY_HOOK }}

      - name: Get deployed commit SHA
        id: deployed_commit
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Wait for site appears online
        uses: kyberorg/wait_for_new_version@v2
        with:
          url: https://yals.ee
          responseCode: 200
          timeout: 120
          interval: 1.5
          hasActuator: true
          commitSha: ${{ steps.deployed_commit.outputs.sha }}
