name: "Ship to Dev System"

on:
  push:
    branches-ignore:
      - trunk

jobs:
  build:
    name: Build JAR
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Complile
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Pass JAR to docker job
        uses: actions/upload-artifact@v2
        with:
          name: yalsee.jar
          path: target/yalsee.jar

  docker:
    name: Docker - build and push to DockerHub
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: yalsee.jar
          path: target/yalsee.jar

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile.DEV
          push: true
          tags: kyberorg/yalsee:dev

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: Deploy image to Dev
    needs: [build, docker]
    runs-on: self-hosted

    steps:
      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEV_DEPLOY_HOOK }}

      - name: Wait for deploy
        run: sleep 120

  testApp:
    name: Run Application Automatic Tests
    needs: [build, docker, deploy]
    runs-on: self-hosted

    steps:
      - name: Test App
        continue-on-error: true
        run:  mvn -Dtest.url=https://dev.yals.ee -Dgrid.hostname=http://127.0.0.1:4444 -Dselenide.browser=chrome -Dtest.buildName=yalsee-${{ env.GITHUB_ACTION }} -Dapp.shortUrl=https://d.yls.ee -Dsurefire.rerunFailingTestsCount=2 clean test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          test_changes_limit: 5
          files: test-results/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
          check_run_annotations: all tests, skipped tests

