name: "Ship to PROD"

on:
  push:
    branches:
      - trunk

jobs:
  ship2prod:
    name: Ship::PROD
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to kio.ee
        run: echo "${{ secrets.KIO_PASS }}" | docker login -u "${{ secrets.KIO_USER }}" --password-stdin kio.ee

      - name: Resolve Dependencies
        run: mvn --batch-mode --update-snapshots dependency:tree

      - name: Compile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Docker build and tag
        run: docker build -f Dockerfile.PROD -t kio.ee/yalsee/yalsee:prod .

      - name: Docker push
        run: docker push kio.ee/yalsee/yalsee:prod

      - name: Delete pushed image to prevent mess
        run: docker rmi kio.ee/yalsee/yalsee:prod
        continue-on-error: true

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.PROD_DEPLOY_HOOK }}

      - name: Get deployed commit SHA
        id: deployed_commit
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Wait for site appears online
        uses: kyberorg/wait_for_new_version@v3
        with:
          url: https://yals.ee
          responseCode: 200
          timeout: 120
          interval: 1.5
          hasActuator: true
          commitSha: ${{ steps.deployed_commit.outputs.sha }}
